const stations = [
  { id: "vancouver:skytrain:expo:waterfront",                name: "Waterfront",                lines: ["expo", "canada"],     slug: "Waterfront_station_(Vancouver)" },
  { id: "vancouver:skytrain:expo:burrard",                   name: "Burrard",                   lines: ["expo"],               slug: "Burrard_station" },
  { id: "vancouver:skytrain:expo:granville",                 name: "Granville",                 lines: ["expo"],               slug: "Granville_station_(SkyTrain)" },
  { id: "vancouver:skytrain:expo:stadium-chinatown",         name: "Stadium–Chinatown",         lines: ["expo"],               slug: "Stadium%E2%80%93Chinatown_station" },
  { id: "vancouver:skytrain:expo:main-street-science-world", name: "Main Street–Science World", lines: ["expo"],               slug: "Main_Street%E2%80%93Science_World_station" },
  { id: "vancouver:skytrain:expo:commercial-broadway",       name: "Commercial–Broadway",       lines: ["expo", "millennium"], slug: "Commercial%E2%80%93Broadway_station" },
  { id: "vancouver:skytrain:expo:nanaimo",                   name: "Nanaimo",                   lines: ["expo"],               slug: "Nanaimo_station" },
  { id: "vancouver:skytrain:expo:29th-avenue",               name: "29th Avenue",               lines: ["expo"],               slug: "29th_Avenue_station" },
  { id: "vancouver:skytrain:expo:joyce-collingwood",         name: "Joyce–Collingwood",         lines: ["expo"],               slug: "Joyce%E2%80%93Collingwood_station" },
  { id: "vancouver:skytrain:expo:patterson",                 name: "Patterson",                 lines: ["expo"],               slug: "Patterson_station_(SkyTrain)" },
  { id: "vancouver:skytrain:expo:metrotown",                 name: "Metrotown",                 lines: ["expo"],               slug: "Metrotown_station" },
  { id: "vancouver:skytrain:expo:royal-oak",                 name: "Royal Oak",                 lines: ["expo"],               slug: "Royal_Oak_station_(SkyTrain)" },
  { id: "vancouver:skytrain:expo:edmonds",                   name: "Edmonds",                   lines: ["expo"],               slug: "Edmonds_station_(SkyTrain)" },
  { id: "vancouver:skytrain:expo:22nd-street",               name: "22nd Street",               lines: ["expo"],               slug: "22nd_Street_station_(SkyTrain)" },
  { id: "vancouver:skytrain:expo:new-westminster",           name: "New Westminster",           lines: ["expo"],               slug: "New_Westminster_station" },
  { id: "vancouver:skytrain:expo:columbia",                  name: "Columbia",                  lines: ["expo"],               slug: "Columbia_station_(SkyTrain)" },
  { id: "vancouver:skytrain:expo:sapperton",                 name: "Sapperton",                 lines: ["expo"],               slug: "Sapperton_station" },
  { id: "vancouver:skytrain:expo:braid",                     name: "Braid",                     lines: ["expo"],               slug: "Braid_station" },
  { id: "vancouver:skytrain:expo:lougheed-town-centre",      name: "Lougheed Town Centre",      lines: ["expo", "millennium"], slug: "Lougheed_Town_Centre_station" },
  { id: "vancouver:skytrain:expo:production-way-university", name: "Production Way–University", lines: ["expo", "millennium"], slug: "Production_Way%E2%80%93University_station" },
  { id: "vancouver:skytrain:expo:scott-road",                name: "Scott Road",                lines: ["expo"],               slug: "Scott_Road_station" },
  { id: "vancouver:skytrain:expo:gateway",                   name: "Gateway",                   lines: ["expo"],               slug: "Gateway_station_(SkyTrain)" },
  { id: "vancouver:skytrain:expo:surrey-central",            name: "Surrey Central",            lines: ["expo"],               slug: "Surrey_Central_station" },
  { id: "vancouver:skytrain:expo:king-george",               name: "King George",               lines: ["expo"],               slug: "King_George_station" },
  { id: "vancouver:skytrain:millennium:vcc-clark",           name: "VCC–Clark",                 lines: ["millennium"],         slug: "VCC%E2%80%93Clark_station" },
  { id: "vancouver:skytrain:millennium:renfrew",             name: "Renfrew",                   lines: ["millennium"],         slug: "Renfrew_station" },
  { id: "vancouver:skytrain:millennium:rupert",              name: "Rupert",                    lines: ["millennium"],         slug: "Rupert_station" },
  { id: "vancouver:skytrain:millennium:gilmore",             name: "Gilmore",                   lines: ["millennium"],         slug: "Gilmore_station_(SkyTrain)" },
  { id: "vancouver:skytrain:millennium:brentwood-town-centre", name: "Brentwood Town Centre",   lines: ["millennium"],         slug: "Brentwood_Town_Centre_station" },
  { id: "vancouver:skytrain:millennium:holdom",              name: "Holdom",                    lines: ["millennium"],         slug: "Holdom_station" },
  { id: "vancouver:skytrain:millennium:sperling-burnaby-lake", name: "Sperling–Burnaby Lake",   lines: ["millennium"],         slug: "Sperling%E2%80%93Burnaby_Lake_station" },
  { id: "vancouver:skytrain:millennium:lake-city-way",       name: "Lake City Way",             lines: ["millennium"],         slug: "Lake_City_Way_station" },
  { id: "vancouver:skytrain:millennium:burquitlam",          name: "Burquitlam",                lines: ["millennium"],         slug: "Burquitlam_station" },
  { id: "vancouver:skytrain:millennium:moody-centre",        name: "Moody Centre",              lines: ["millennium"],         slug: "Moody_Centre_station" },
  { id: "vancouver:skytrain:millennium:inlet-centre",        name: "Inlet Centre",              lines: ["millennium"],         slug: "Inlet_Centre_station" },
  { id: "vancouver:skytrain:millennium:coquitlam-central",   name: "Coquitlam Central",         lines: ["millennium"],         slug: "Coquitlam_Central_station" },
  { id: "vancouver:skytrain:millennium:lincoln",             name: "Lincoln",                   lines: ["millennium"],         slug: "Lincoln_station_(SkyTrain)" },
  { id: "vancouver:skytrain:millennium:lafarge-lake-douglas", name: "Lafarge Lake–Douglas",     lines: ["millennium"],         slug: "Lafarge_Lake%E2%80%93Douglas_station" },
  { id: "vancouver:skytrain:canada:vancouver-city-centre",   name: "Vancouver City Centre",     lines: ["canada"],             slug: "Vancouver_City_Centre_station" },
  { id: "vancouver:skytrain:canada:yaletown-roundhouse",     name: "Yaletown–Roundhouse",       lines: ["canada"],             slug: "Yaletown%E2%80%93Roundhouse_station" },
  { id: "vancouver:skytrain:canada:olympic-village",         name: "Olympic Village",           lines: ["canada"],             slug: "Olympic_Village_station" },
  { id: "vancouver:skytrain:canada:broadway-city-hall",      name: "Broadway–City Hall",        lines: ["canada"],             slug: "Broadway%E2%80%93City_Hall_station" },
  { id: "vancouver:skytrain:canada:king-edward",             name: "King Edward",               lines: ["canada"],             slug: "King_Edward_station" },
  { id: "vancouver:skytrain:canada:oakridge-41st-avenue",    name: "Oakridge–41st Avenue",      lines: ["canada"],             slug: "Oakridge%E2%80%9341st_Avenue_station" },
  { id: "vancouver:skytrain:canada:langara-49th-avenue",     name: "Langara–49th Avenue",       lines: ["canada"],             slug: "Langara%E2%80%9349th_Avenue_station" },
  { id: "vancouver:skytrain:canada:marine-drive",            name: "Marine Drive",              lines: ["canada"],             slug: "Marine_Drive_station" },
  { id: "vancouver:skytrain:canada:bridgeport",              name: "Bridgeport",                lines: ["canada"],             slug: "Bridgeport_station_(SkyTrain)" },
  { id: "vancouver:skytrain:canada:aberdeen",                name: "Aberdeen",                  lines: ["canada"],             slug: "Aberdeen_station_(SkyTrain)" },
  { id: "vancouver:skytrain:canada:lansdowne",               name: "Lansdowne",                 lines: ["canada"],             slug: "Lansdowne_station_(SkyTrain)" },
  { id: "vancouver:skytrain:canada:capstan",                 name: "Capstan",                   lines: ["canada"],             slug: "Capstan_station" },
  { id: "vancouver:skytrain:canada:richmond-brighouse",      name: "Richmond–Brighouse",        lines: ["canada"],             slug: "Richmond%E2%80%93Brighouse_station" },
  { id: "vancouver:skytrain:canada:templeton",               name: "Templeton",                 lines: ["canada"],             slug: "Templeton_station" },
  { id: "vancouver:skytrain:canada:sea-island-centre",       name: "Sea Island Centre",         lines: ["canada"],             slug: "Sea_Island_Centre_station" },
  { id: "vancouver:skytrain:canada:yvr-airport",             name: "YVR–Airport",               lines: ["canada"],             slug: "YVR%E2%80%93Airport_station" },
];

export default {
  city_id:   "vancouver",
  system_id: "skytrain",
  stations,
};
