// Vancouver SkyTrain — Expo, Millennium, and Canada Lines (54 stations).
const stations = [
  { name: "Waterfront",                lines: ["expo", "canada"],     slug: "Waterfront_station_(Vancouver)" },
  { name: "Burrard",                   lines: ["expo"],               slug: "Burrard_station" },
  { name: "Granville",                 lines: ["expo"],               slug: "Granville_station_(SkyTrain)" },
  { name: "Stadium–Chinatown",         lines: ["expo"],               slug: "Stadium%E2%80%93Chinatown_station" },
  { name: "Main Street–Science World", lines: ["expo"],               slug: "Main_Street%E2%80%93Science_World_station" },
  { name: "Commercial–Broadway",       lines: ["expo", "millennium"], slug: "Commercial%E2%80%93Broadway_station" },
  { name: "Nanaimo",                   lines: ["expo"],               slug: "Nanaimo_station" },
  { name: "29th Avenue",               lines: ["expo"],               slug: "29th_Avenue_station" },
  { name: "Joyce–Collingwood",         lines: ["expo"],               slug: "Joyce%E2%80%93Collingwood_station" },
  { name: "Patterson",                 lines: ["expo"],               slug: "Patterson_station_(SkyTrain)" },
  { name: "Metrotown",                 lines: ["expo"],               slug: "Metrotown_station" },
  { name: "Royal Oak",                 lines: ["expo"],               slug: "Royal_Oak_station_(SkyTrain)" },
  { name: "Edmonds",                   lines: ["expo"],               slug: "Edmonds_station_(SkyTrain)" },
  { name: "22nd Street",               lines: ["expo"],               slug: "22nd_Street_station_(SkyTrain)" },
  { name: "New Westminster",           lines: ["expo"],               slug: "New_Westminster_station" },
  { name: "Columbia",                  lines: ["expo"],               slug: "Columbia_station_(SkyTrain)" },
  { name: "Sapperton",                 lines: ["expo"],               slug: "Sapperton_station" },
  { name: "Braid",                     lines: ["expo"],               slug: "Braid_station" },
  { name: "Lougheed Town Centre",      lines: ["expo", "millennium"], slug: "Lougheed_Town_Centre_station" },
  { name: "Production Way–University", lines: ["expo", "millennium"], slug: "Production_Way%E2%80%93University_station" },
  { name: "Scott Road",                lines: ["expo"],               slug: "Scott_Road_station" },
  { name: "Gateway",                   lines: ["expo"],               slug: "Gateway_station_(SkyTrain)" },
  { name: "Surrey Central",            lines: ["expo"],               slug: "Surrey_Central_station" },
  { name: "King George",               lines: ["expo"],               slug: "King_George_station" },
  { name: "VCC–Clark",                 lines: ["millennium"],         slug: "VCC%E2%80%93Clark_station" },
  { name: "Renfrew",                   lines: ["millennium"],         slug: "Renfrew_station" },
  { name: "Rupert",                    lines: ["millennium"],         slug: "Rupert_station" },
  { name: "Gilmore",                   lines: ["millennium"],         slug: "Gilmore_station_(SkyTrain)" },
  { name: "Brentwood Town Centre",     lines: ["millennium"],         slug: "Brentwood_Town_Centre_station" },
  { name: "Holdom",                    lines: ["millennium"],         slug: "Holdom_station" },
  { name: "Sperling–Burnaby Lake",     lines: ["millennium"],         slug: "Sperling%E2%80%93Burnaby_Lake_station" },
  { name: "Lake City Way",             lines: ["millennium"],         slug: "Lake_City_Way_station" },
  { name: "Burquitlam",                lines: ["millennium"],         slug: "Burquitlam_station" },
  { name: "Moody Centre",              lines: ["millennium"],         slug: "Moody_Centre_station" },
  { name: "Inlet Centre",              lines: ["millennium"],         slug: "Inlet_Centre_station" },
  { name: "Coquitlam Central",         lines: ["millennium"],         slug: "Coquitlam_Central_station" },
  { name: "Lincoln",                   lines: ["millennium"],         slug: "Lincoln_station_(SkyTrain)" },
  { name: "Lafarge Lake–Douglas",      lines: ["millennium"],         slug: "Lafarge_Lake%E2%80%93Douglas_station" },
  { name: "Vancouver City Centre",     lines: ["canada"],             slug: "Vancouver_City_Centre_station" },
  { name: "Yaletown–Roundhouse",       lines: ["canada"],             slug: "Yaletown%E2%80%93Roundhouse_station" },
  { name: "Olympic Village",           lines: ["canada"],             slug: "Olympic_Village_station" },
  { name: "Broadway–City Hall",        lines: ["canada"],             slug: "Broadway%E2%80%93City_Hall_station" },
  { name: "King Edward",               lines: ["canada"],             slug: "King_Edward_station" },
  { name: "Oakridge–41st Avenue",      lines: ["canada"],             slug: "Oakridge%E2%80%9341st_Avenue_station" },
  { name: "Langara–49th Avenue",       lines: ["canada"],             slug: "Langara%E2%80%9349th_Avenue_station" },
  { name: "Marine Drive",              lines: ["canada"],             slug: "Marine_Drive_station" },
  { name: "Bridgeport",                lines: ["canada"],             slug: "Bridgeport_station_(SkyTrain)" },
  { name: "Aberdeen",                  lines: ["canada"],             slug: "Aberdeen_station_(SkyTrain)" },
  { name: "Lansdowne",                 lines: ["canada"],             slug: "Lansdowne_station_(SkyTrain)" },
  { name: "Capstan",                   lines: ["canada"],             slug: "Capstan_station" },
  { name: "Richmond–Brighouse",        lines: ["canada"],             slug: "Richmond%E2%80%93Brighouse_station" },
  { name: "Templeton",                 lines: ["canada"],             slug: "Templeton_station" },
  { name: "Sea Island Centre",         lines: ["canada"],             slug: "Sea_Island_Centre_station" },
  { name: "YVR–Airport",               lines: ["canada"],             slug: "YVR%E2%80%93Airport_station" },
];

const lineInfo = {
  expo:       { name: "Expo",       color: "#1565C0", bg: "rgba(21, 101, 192, 0.12)" },
  millennium: { name: "Millennium", color: "#FFB300", bg: "rgba(255, 179, 0, 0.18)"  },
  canada:     { name: "Canada",     color: "#00A887", bg: "rgba(0, 168, 135, 0.14)"  },
};

export default {
  id: "vancouver",
  name: "Vancouver",
  systemName: "SkyTrain",
  brandTitle: "SkyTrain Showdown",
  selectorLabel: "Vancouver · SkyTrain",
  stations,
  lineInfo,
};
